### ISSUE TITLE
Privacy Center not looking for correct variable

### ISSUE THREAD

**Issue by nicolas-ethyca** [ethyca/fides-helm#15]
### Bug Description

_A description of what the bug is._

#### Steps to Reproduce

1. Set server url in config JSON using provided variables
2. it fails

### Expected behavior
1. It works 
### Screenshots

_If applicable, add screenshots to help explain your problem._

Appears to be looking for a different variable.

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/111306317/214588151-372b535f-1f7f-4aa0-bfa6-e6ede1437489.png">

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

**Comment by RobertKeyser** [comment]
@nicolas-ethyca interesting. The old config key (which are still used in this Helm chart) was `fidesops_host_production`. The new config key is `server_url_production`.

According to the code, it looks like both are still in there, but perhaps something is getting in its way. Either way, I can patch the Helm chart to fix this.

https://github.com/ethyca/fides/blob/4d66b4357d7f23179a1433b05b5790b2bac84c55/clients/privacy-center/constants/index.ts#L11

**Comment by RobertKeyser** [comment]
@nicolas-ethyca, the latest versions of the helm chart have the vars set as `server_url_production`. Which version of the chart was this discovered in?
